#!/bin/bash
#
# Generate index.html listing all talks (20*.html in repo root),
# styled to loosely match https://centerforopenneuroscience.org/.
#
# Usage: tools/create_index.sh   (run from repo root, or anywhere)

set -eu

# Resolve repo root (parent of tools/)
REPO_ROOT="$(cd "$(dirname "$(realpath "$0")")/.." && pwd)"
cd "$REPO_ROOT"

OUT="index.html"

# Extract title from an HTML file: first <title>...</title>, fall back to filename.
extract_title() {
    local f="$1" t
    t=$(sed -n 's:.*<title>\(.*\)</title>.*:\1:p' "$f" | head -n1)
    if [ -z "$t" ]; then
        t=$(basename "$f" .html)
    fi
    # Strip leading/trailing whitespace
    echo "$t" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

# HTML-escape a string (&, <, >, ", ')
html_escape() {
    sed -e 's/&/\&amp;/g' \
        -e 's/</\&lt;/g' \
        -e 's/>/\&gt;/g' \
        -e 's/"/\&quot;/g' \
        -e "s/'/\&#39;/g"
}

# Collect & sort talks (reverse: newest first)
mapfile -t TALKS < <(ls -1 20*.html 2>/dev/null | sort -r)

if [ "${#TALKS[@]}" -eq 0 ]; then
    echo "No 20*.html talks found in $REPO_ROOT" >&2
    exit 1
fi

# Build list items grouped by year
list_items=""
prev_year=""
for f in "${TALKS[@]}"; do
    year="${f:0:4}"
    title=$(extract_title "$f" | html_escape)
    name_escaped=$(echo "$f" | html_escape)
    if [ "$year" != "$prev_year" ]; then
        if [ -n "$prev_year" ]; then
            list_items+="      </ul>"$'\n'
        fi
        list_items+="      <h2>${year}</h2>"$'\n'
        list_items+="      <ul class=\"talks\">"$'\n'
        prev_year="$year"
    fi
    list_items+="        <li><a href=\"${name_escaped}\">${title}</a> <span class=\"file\">${name_escaped}</span></li>"$'\n'
done
list_items+="      </ul>"$'\n'

cat > "$OUT" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>CON Talks</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" type="text/css">
  <style>
    /* Loose visual rhyme with https://centerforopenneuroscience.org/ */
    :root {
      --con-blue: #87AADE;
      --con-dark: #38434C;
      --con-text: #333;
      --con-muted: #777;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: 'Open Sans', -apple-system, BlinkMacSystemFont, sans-serif;
      font-weight: 400;
      color: var(--con-text);
      background: #fff;
      line-height: 1.5;
    }
    header {
      background: var(--con-blue);
      color: #fff;
      padding: 2em 1em;
    }
    header .inner { max-width: 960px; margin: 0 auto; }
    header h1 {
      margin: 0;
      font-weight: 600;
      font-size: 2em;
    }
    header h1 a { color: #fff; text-decoration: none; }
    header p {
      margin: 0.25em 0 0 0;
      font-weight: 300;
      font-size: 1.1em;
      opacity: 0.95;
    }
    main {
      max-width: 960px;
      margin: 0 auto;
      padding: 2em 1em 4em 1em;
    }
    main h2 {
      font-weight: 600;
      color: var(--con-dark);
      border-bottom: 2px solid var(--con-blue);
      padding-bottom: 0.25em;
      margin-top: 1.75em;
    }
    ul.talks {
      list-style: none;
      padding: 0;
      margin: 0.5em 0;
    }
    ul.talks li {
      padding: 0.5em 0;
      border-bottom: 1px solid #eee;
    }
    ul.talks a {
      color: var(--con-dark);
      text-decoration: none;
      font-weight: 600;
    }
    ul.talks a:hover { color: var(--con-blue); text-decoration: underline; }
    ul.talks .file {
      display: block;
      font-family: 'Source Code Pro', monospace;
      font-size: 0.85em;
      color: var(--con-muted);
      font-weight: 400;
    }
    footer {
      background: var(--con-dark);
      color: #fff;
      padding: 1.5em 1em;
      font-size: 0.9em;
    }
    footer .inner { max-width: 960px; margin: 0 auto; }
    footer a { color: var(--con-blue); }
  </style>
</head>
<body>
  <header>
    <div class="inner">
      <h1><a href="https://centerforopenneuroscience.org/">Center for Open Neuroscience</a></h1>
      <p>Talks &amp; slide decks</p>
    </div>
  </header>
  <main>
    <p>Slides from talks and workshops by CON people. This location is also a DataLad dataset (git/git-annex repository) so you can datalad clone it to get all the sources and materials.</p>
${list_items}  </main>
  <footer>
    <div class="inner">
      Auto-generated by <code>tools/create_index.sh</code>.
    </div>
  </footer>
</body>
</html>
HTML

echo "Wrote $OUT with ${#TALKS[@]} talk(s)."
